server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.15.92.108:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: admin
    password: a123456

